name: epf_africa
description: EPF Africa Q&A Platform

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP & Networking
  http: ^1.1.0
  
  # State Management
  provider: ^6.0.5
  
  # Local Storage
  shared_preferences: ^2.2.0
  
  # UI & Utilities
  intl: ^0.18.1
  
  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/fonts/
